title: holu
email: hello@holudelivery.com
description: >
  deliveries in minutes for your e-commerce business
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: holudelivery
github_username:  holudelivery
